# Home Manager module for LazyVim.
# "Install with Nix, configure with Lua" — neovim and tools come from Nix;
# plugins are managed by lazy.nvim at runtime; configuration lives in the
# Lua files under ./nvim/.
#
# Usage: import this file in the user's home.nix:
#   imports = [ ../../../modules/home/apps/editors/lazyvim ];
#
# When imported, common.nix's default programs.neovim stays active, but
# LazyVim's init.lua (linked via xdg.configFile) replaces the init.vim
# generated by home-manager (neovim loads init.lua with priority).
{ pkgs, ... }:

{
  programs.neovim = {
    # Packages that need to be on the rtp but aren't managed by lazy.nvim.
    # Neovim loads them before init.lua via the home-manager wrapper.
    plugins = [
      # Tree-sitter grammar for Gregorio (GABC/NABC) precompiled by Nix.
      # nvim-treesitter finds the parser at <rtp>/parser/gregorio.so.
      pkgs.tree-sitter-gregorio-nvim
    ];
  };

  # Tools installed via Nix, available on PATH for Neovim.
  home.packages = with pkgs; [
    # ── LSP servers ──────────────────────────────────────────────────────
    lua-language-server
    nil # nil_ls: lightweight and fast Nix LSP
    nixd # nixd: Nix LSP with flake + NixOS/HM option awareness
    marksman # Markdown
    yaml-language-server
    bash-language-server
    vscode-langservers-extracted # html, css, json, eslint
    texlab # LaTeX
    rust-analyzer # Rust (complements rustup)
    # ── Formatters and linters ───────────────────────────────────────────
    stylua # Lua
    prettier # JSON, YAML, Markdown, HTML, CSS
    shfmt # Shell
    nixfmt # Nix (RFC 166)
    # ── Support tools ─────────────────────────────────────────────────────
    lazygit # TUI git (integrated with LazyVim)
    gcc # C compiler so nvim-treesitter can build new grammars
    # ── Gregorio ─────────────────────────────────────────────────────────
    gregorio-lsp
  ];

  # LazyVim config: Lua files linked via xdg.configFile.
  # recursive = true: each file under ./nvim/ becomes an individual symlink
  # in ~/.config/nvim/; intermediate directories are created as real
  # directories, allowing lazy.nvim to write lazy-lock.json in the same directory.
  xdg.configFile."nvim" = {
    source = ./nvim;
    recursive = true;
  };

  # Nix store paths injected as a Lua module.
  # Accessible from any lazy.nvim spec via: local nix = require("nix.paths")
  xdg.configFile."nvim/lua/nix/paths.lua".text = ''
    -- Generated by Nix — do not edit manually.
    return {
      gregorio_nvim = "${pkgs.gregorio-nvim}",
      gregorio_lsp  = "${pkgs.gregorio-lsp}/bin/gregorio-lsp",
      nixfmt        = "${pkgs.nixfmt}/bin/nixfmt",
      nil_ls        = "${pkgs.nil}/bin/nil",
      nixd          = "${pkgs.nixd}/bin/nixd",
    }
  '';
}
