keys:
  - &system age1j7rrmh4hcqhxtw5ufltzl6qhc53kmyy3dahndtfgmf25xt79uswqyj28zy
  - &abutre age1mxfsahqh9p8dp4v2eg67xyxamulqg0aquh54z8p2zxtqjdcchvfskmqa0u

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *system
  - path_regex: private/sops/home/abutre/.*\.(yaml|json|env|ini|conf)$
    key_groups:
      - age:
          - *abutre
