-- Overrides for Nix: nixd (LSP with flake and NixOS/HM option awareness)
-- and nil_ls (lightweight fallback). Paths injected via nix/paths.lua generated by Nix.
local paths = require("nix.paths")

return {
  -- ── nixd: replaces the default config from the lang.nix extra ─────────
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        nixd = {
          mason = false,
          cmd = { paths.nixd },
          settings = {
            nixd = {
              nixpkgs = {
                -- Resolves nixpkgs from the system configuration's flake
                expr = 'import (builtins.getFlake "/etc/nixos").inputs.nixpkgs { }',
              },
              formatting = {
                command = { paths.nixfmt, "--stdin" },
              },
              options = {
                nixos = {
                  expr = '(builtins.getFlake "/etc/nixos").nixosConfigurations.barbudus.options',
                },
                home_manager = {
                  expr = '(builtins.getFlake "/etc/nixos").homeConfigurations."abutre@barbudus".options',
                },
              },
            },
          },
        },
        nil_ls = {
          mason = false,
          cmd = { paths.nil_ls },
        },
      },
    },
  },
  -- ── conform: uses nixfmt (RFC 166) to format Nix files ─────────────────
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        nix = { paths.nixfmt },
      },
    },
  },
}
