# Preservation module for ZFS: ephemeral system with a ZFS dataset on the root
# The root (/) is a ZFS dataset reverted to the @blank snapshot on every
# boot in the initrd. This automatically wipes ephemeral state without
# needing tmpfs. Important data is preserved in /persist via bind mounts
# managed by the nix-community/preservation module.
#
# Differences from the Btrfs+tmpfs profile (preservation.nix):
#   • The root uses ZFS (zroot/local/root dataset) instead of tmpfs
#   • Rollback is done via boot.initrd.postDeviceCommands (legacy initrd)
#     or via a systemd service in the initrd (when boot.initrd.systemd.enable = true)
#   • The ZFS hostId (networking.hostId) must be set in the host configuration
#
# Prerequisites:
#   • networking.hostId must be set (generated by install.sh or manually:
#     head -c4 /dev/urandom | od -A none -t x4 | tr -d ' ')
#   • The zroot/local/root@blank dataset must exist (created by disko-zfs.nix)
{ lib, ... }:

{
  # Enable ZFS support in the kernel and userspace tools
  boot.supportedFilesystems = [ "zfs" ];

  # Roll back the root dataset to the @blank snapshot in the legacy
  # (non-systemd) initrd. lib.mkAfter ensures this command runs AFTER the
  # ZFS pool import by the initrd (which happens in NixOS's default
  # postDeviceCommands with ZFS).
  #
  # For systems with boot.initrd.systemd.enable = true, comment out this
  # block and use the systemd service below (boot.initrd.systemd.services.rollback).
  boot.initrd.postDeviceCommands = lib.mkAfter ''
    zfs rollback -r zroot/local/root@blank
  '';

  # Alternative for systemd initrd (boot.initrd.systemd.enable = true):
  # Uncomment the block below and comment out boot.initrd.postDeviceCommands above.
  #
  # boot.initrd.systemd.services.rollback = {
  #   description = "Roll back the ZFS root dataset to the @blank snapshot";
  #   wantedBy = [ "initrd.target" ];
  #   after = [ "zfs-import-zroot.service" ];
  #   before = [ "sysroot.mount" ];
  #   unitConfig.DefaultDependencies = "no";
  #   serviceConfig.Type = "oneshot";
  #   script = ''
  #     zfs rollback -r zroot/local/root@blank
  #   '';
  # };

  # /persist must be available at boot (preservation needs it to set up the
  # bind mounts before any service starts).
  # /home doesn't need neededForBoot — it's recreated by preservation via tmpfiles.
  fileSystems."/persist".neededForBoot = true;

  # preservation module configuration
  # Defines which files and directories are preserved across boots
  preservation.preserveAt."/persist" = {
    # System directories to preserve
    directories = [
      "/etc/nixos" # NixOS configuration
      "/etc/NetworkManager/system-connections" # Saved network connections
      "/var/lib/systemd" # systemd state
      "/var/lib/nixos" # NixOS internal state
      "/var/lib/bluetooth" # Paired Bluetooth devices
      "/var/db/sudo" # sudo timestamps
    ];

    # System files to preserve
    files = [
      "/etc/machine-id" # Unique machine ID
      # NOTE: /etc/shadow is NOT managed here.
      # The users module (users.nix) defines a 'restoreShadow' activation
      # script with deps = ["users"] that, after NixOS's 'users' activation
      # script (which does an atomic rename of /etc/shadow), copies
      # /persist/etc/shadow → /etc/shadow. This ensures password changes
      # via 'passwd' are persisted to /persist/etc/shadow.
    ];
  };
}
